
import { Agent, FlowerTheme, Localization, Language } from './types';

export const LOCALIZATION: Record<Language, Localization> = {
  en: {
    title: 'Floral Analyst',
    workflow: 'Workflow',
    dashboard: 'Dashboard',
    settings: 'Settings',
    style: 'Flower Style',
    language: 'Language',
    mode: 'Appearance',
    uploadDocument: 'Upload Document',
    uploadHint: 'Upload PDF, TXT, JSON, MD',
    documentControl: 'Document Viewer',
    addAgent: 'Add Agent',
    agentWorkflow: 'Agent Workflow',
    runWorkflow: 'Run Agents',
    running: 'Processing...',
    resultsDashboard: 'Insights Dashboard',
    extractedEntities: 'Extracted Entities',
    sentimentAnalysis: 'Sentiment Analysis',
    apiKeySettings: 'API Keys',
    apiKeyHint: 'Your keys are stored locally in your browser.',
    saveKeys: 'Save Credentials',
    summary: 'Document Summary',
    generatingSummary: 'Generating summary...',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    page: 'Page',
    luckWheel: 'Style Wheel',
    spin: 'Spin!',
    maxTokens: 'Max Tokens',
    model: 'Model',
    prompt: 'System Prompt',
    smartNote: 'Smart Note',
    ocrThisPage: 'OCR This Page',
    ocrProcessing: 'Scanning Page...',
    ocrSuccess: 'Text added to document!',
    formatNote: 'AI Smart Format',
    extractEntities: 'Extract 20 Entities',
    highlightColor: 'Highlight Color',
    keyword: 'Keyword',
    addHighlight: 'Add',
    markdownPreview: 'Markdown Preview',
    entityTable: 'Entity Table',
    entityJson: 'JSON View',
    editOutput: 'Edit Output',
    preview: 'Preview',
    save: 'Save Changes',
    cancel: 'Cancel',
    edit: 'Edit',
  },
  'zh-TW': {
    title: '花語分析師',
    workflow: '工作流程',
    dashboard: '儀表板',
    settings: '設定',
    style: '花語風格',
    language: '語言',
    mode: '外觀模式',
    uploadDocument: '上傳文件',
    uploadHint: '上傳 PDF, TXT, JSON, MD',
    documentControl: '文件檢視器',
    addAgent: '新增代理',
    agentWorkflow: '代理工作流',
    runWorkflow: '執行代理',
    running: '處理中...',
    resultsDashboard: '洞察儀表板',
    extractedEntities: '實體擷取',
    sentimentAnalysis: '情感分析',
    apiKeySettings: 'API 金鑰',
    apiKeyHint: '您的金鑰僅儲存在本地瀏覽器中。',
    saveKeys: '儲存憑證',
    summary: '文件摘要',
    generatingSummary: '正在產生摘要...',
    zoomIn: '放大',
    zoomOut: '縮小',
    page: '頁次',
    luckWheel: '風格幸運輪',
    spin: '旋轉!',
    maxTokens: '最大標記數',
    model: '模型',
    prompt: '系統提示詞',
    smartNote: '智慧筆記',
    ocrThisPage: 'OCR 此頁面',
    ocrProcessing: '掃描中...',
    ocrSuccess: '文字已新增！',
    formatNote: 'AI 智慧排版',
    extractEntities: '提取 20 個實體',
    highlightColor: '標記顏色',
    keyword: '關鍵字',
    addHighlight: '新增',
    markdownPreview: 'Markdown 預覽',
    entityTable: '實體表格',
    entityJson: 'JSON 檢視',
    editOutput: '編輯輸出',
    preview: '預覽',
    save: '儲存變更',
    cancel: '取消',
    edit: '編輯',
  },
};

export const FLOWER_THEMES: FlowerTheme[] = [
  { name: 'Red Rose', primary: '#e11d48', secondary: '#fda4af', surface: '#fff1f2', text: '#881337' },
  { name: 'Sunflower', primary: '#d97706', secondary: '#fde68a', surface: '#fffbeb', text: '#78350f' },
  { name: 'Lavender', primary: '#7c3aed', secondary: '#c4b5fd', surface: '#f5f3ff', text: '#4c1d95' },
  { name: 'Sakura', primary: '#ec4899', secondary: '#fbcfe8', surface: '#fdf2f8', text: '#831843' },
  { name: 'Lily', primary: '#059669', secondary: '#6ee7b7', surface: '#ecfdf5', text: '#064e3b' },
  { name: 'Bluebell', primary: '#2563eb', secondary: '#93c5fd', surface: '#eff6ff', text: '#1e3a8a' },
  { name: 'Tulip', primary: '#db2777', secondary: '#f9a8d4', surface: '#fdf2f8', text: '#831843' },
  { name: 'Daisy', primary: '#f59e0b', secondary: '#fcd34d', surface: '#fffbeb', text: '#78350f' },
  { name: 'Orchid', primary: '#9333ea', secondary: '#d8b4fe', surface: '#faf5ff', text: '#581c87' },
  { name: 'Peony', primary: '#be185d', secondary: '#f9a8d4', surface: '#fdf2f8', text: '#831843' },
  { name: 'Hydrangea', primary: '#3b82f6', secondary: '#93c5fd', surface: '#eff6ff', text: '#1e40af' },
  { name: 'Marigold', primary: '#ea580c', secondary: '#fdba74', surface: '#fff7ed', text: '#7c2d12' },
  { name: 'Violet', primary: '#6d28d9', secondary: '#a78bfa', surface: '#f5f3ff', text: '#4c1d95' },
  { name: 'Iris', primary: '#4338ca', secondary: '#818cf8', surface: '#eef2ff', text: '#312e81' },
  { name: 'Poppy', primary: '#dc2626', secondary: '#fca5a5', surface: '#fef2f2', text: '#7f1d1d' },
  { name: 'Jasmine', primary: '#0d9488', secondary: '#5eead4', surface: '#f0fdfa', text: '#134e4a' },
  { name: 'Daffodil', primary: '#ca8a04', secondary: '#fde047', surface: '#fefce8', text: '#713f12' },
  { name: 'Lotus', primary: '#be123c', secondary: '#fda4af', surface: '#fff1f2', text: '#881337' },
  { name: 'Hibiscus', primary: '#b91c1c', secondary: '#fca5a5', surface: '#fef2f2', text: '#7f1d1d' },
  { name: 'Magnolia', primary: '#db2777', secondary: '#fbcfe8', surface: '#fdf2f8', text: '#831843' },
];

export const MODEL_OPTIONS = [
  { value: 'gemini/gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
  { value: 'gemini/gemini-2.5-flash-thinking', label: 'Gemini 2.5 Flash Thinking' },
  { value: 'openai/gpt-4o-mini', label: 'OpenAI GPT-4o Mini' },
  { value: 'openai/gpt-4o', label: 'OpenAI GPT-4o' },
];

export const DEFAULT_AGENTS: Omit<Agent, 'id' | 'status' | 'output' | 'error' | 'outputJson' | 'model' | 'maxTokens'>[] = [
  {
    name: 'Sentiment Analyzer',
    prompt: 'Analyze the sentiment of the text. Return JSON format: { "sentiment": "positive" | "negative" | "neutral", "confidence": number }.',
  },
  {
    name: 'Entity Extractor',
    prompt: 'Extract key entities (people, organizations, locations). Return JSON array: [{ "name": "...", "type": "..." }].',
  },
  {
    name: 'Summarizer',
    prompt: 'Provide a concise bullet-point summary of the key arguments in the text.',
  },
];
